version: "3"
services:
 mymongodb:
   image: mongo:latest
   container_name: "mymongodb"
   ports:
     - 27017:27017
 springboot-api:
   image: springboot-api:latest
   container_name: springboot-api
   ports:
     - 8080:8080
   links:
     - mymongodb